language: ruby
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.8.0
  - jruby-head
  - ruby-head
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_edge.gemfile
sudo: false
install:
  - bundle install --jobs=8 --retry=3
script:
  - bundle exec rake
after_script:
  - bundle exec rake benchmark
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - gemfile: gemfiles/rails_edge.gemfile
    # Wait for activerecord-jdbcsqlite3-adapter's support
    # https://github.com/jruby/activerecord-jdbc-adapter/labels/rails-5.x
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: jruby-9.1.8.0
      gemfile: gemfiles/rails_5.1.gemfile
